import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "Aima Ovai's Portfolio",
  description: "Generated by Aima Ovai",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        
        <div className="landing-container">
          <div className="animated-gradient" />
        </div>
        {children}
      </body>
    </html>
  );
}
